### ISSUE TITLE
Fix cswap_constant_time_is_correct proof

### ISSUE THREAD

**Issue by atrieu** [franziskuskiefer/the-hacl-approach#1]
Hi, just read your blogpost on HACL*, very interesting.

I'm not a F* expert, but i'm not sure I understand the requires in `cswap_constant_time_is_correct`:
https://github.com/franziskuskiefer/the-hacl-approach/blob/5c03b4ec7330c29ed6f7b14d6041ddeef3cdbdc9/Impl.CSwap.fst#L69-L71

If I understand correctly, you're actually proving if x = y and c = 0 then `cswap_constant_time` verifies the spec, you're not proving that it verifies the spec in all possible cases.

**Comment by franziskuskiefer** [comment]
You're of course absolutely right 🤦‍♂️ I committed an incomplete state. I fixed the conditions but it doesn't export or verify right now for me. I have to find a minute later to fix  it up.

**Comment by atrieu** [comment]
https://github.com/franziskuskiefer/the-hacl-approach/blob/72ef245f2bfb9c3b5d200e9dda8cbc34d056250c/Impl.CSwap.fst#L72

I think it doesn't verify because it's false ;-)
It should just be `a = c /\ b = d` without any if condition.
Btw, in the if condition, I think the `c` you're trying to refer to is the parameter of the lemma, but it's hidden by the let binding you use just before in `let c, d = cswap x y c in`

**Comment by franziskuskiefer** [comment]
🤦‍♂️^2 I shouldn't try to do something like this during breakfast. The original `a = c /\ b = d` was fine as you said. I forgot to add `xor_rules x y c` to make it verify. This is fixed in f29ea219aaa4979160a0afcd211e164315e93b07

**Comment by franziskuskiefer** [comment]
Thanks for bringing this up!
